### ISSUE TITLE
Proposal: Cryptocurrency -> Risk

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#13]
As per Zack White's suggestion, we should have a "risk" section in the education guide.

> I think having a "Risk" section on crytpo/blockchain would be necessary. It goes hand and hand with the education portion and having proper understanding on what youre investing in. It will also give your readers a sense that you are looking out for them and have their best interest at hand.

I think this is a worthwhile section that can contain content that is written in a way as to not scare of people.

**Comment by nkmlombardi** [comment]
#30

**Comment by kmanc** [comment]
This got merged with our last round of commits
