### ISSUE TITLE
Retrieve ICO dates

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#2]
Currently we only have symbol, name, blockchain and a description of 69 ICO tokens. We don't have any dates related to them. We need:
- Date of crowdfund
- Initial supply
- Link to website

It's impossible to automate this section of the site, it will need to be manually updated as new ICO's are announced. The first bulk of the data is going to be the hardest part, trickling them in afterwards and keeping it updated is easier.

Current state of ICO list: https://github.com/blockstreet/content/blob/staging/ico/index.json

**Comment by Suhmedoh** [comment]
not sure how worth it this is:  I don't believe we should try to stay on top of every ICO coming out; so many of them are just quick money grabs, or they just disappear before/after the crowd sale.  I went through the list and found it difficult to get the specific information(some of them didn't even have a functioning website, I could only find broken links from other sites).  I think if we want to display ICO info, we should do it for ones that we think are legitimate and have value one way or another, and ignore the small/scammy ones.

**Comment by mattbloom** [comment]
I'd agree ICOs are getting out of hand but there is probably some interesting news to cover as it relates to ICO and crypto regulation or legitimate companies and projects like Filecoin who are actually backed by VCs. Enterprises are increasingly looking for guidance and a way to understand who is legit in this space...this might be a larger discussion about what sort of news or content we want to consistently update (and outsource) on the site.

**Comment by nkmlombardi** [comment]
Deferred
