### ISSUE TITLE
Simplify: Cryptocurrency -> Initial Coin Offering

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#21]
The verbiage on this page needs to be toned down to a lower reading level.

**Comment by kmanc** [comment]
Agreed. I haven't looked ay anything under the cryptocurrency folder...its gonna need some work

**Comment by kmanc** [comment]
Every file in that directory needs to be fixed pretty much. Want to nail down BC first though

**Comment by mattbloom** [comment]
I'll tackle some of this (I know I can get wordy in my writing) -- anything specific standout?

**Comment by kmanc** [comment]
Done this week with all the work put into education
