### ISSUE TITLE
Converge on cryptocurrency terminology

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#33]
Current synonyms I've seen us use throughout the education section:
- Cryptocurrency
- Crypto-coin
- Coin
- Currency
- Crypto-asset
- Asset

Cryptocurrency in my opinion is the most expressive version of it (and the most technical term), but it's a pain in the ass to both write and read. In my opinion:

Ethereum, Bitcoin, and other currencies tied to a **platform** are cryptocurrencies.
Augur, Firstblood and Golem which exist **on** a platform are all tokens (derived from their technical name: ERC20 Token)

These two (Cryptocurrencies & Tokens) are both under the roof of Crypto Assets.

---

Let me know what you guys think. There'll be an effort to sweep the education section to correct our terminology through, and henceforth.

**Comment by kmanc** [comment]
Strongly oppose using the word asset anywhere we expect education readers to be. Too intimidating to the uninitiated

**Comment by mattbloom** [comment]
Yeah I agree the term asset can be ignored for education. Do you think adding a small 'key words' section at the beginning or end of education page would be necessary? (don't want it to feel like a textbook though with the 'what did we learn?' recap)  I'd also make the distinction between distributed ledgers and blockchains - since blockchains are a type of distributed ledger

**Comment by kmanc** [comment]
I think that could be a good idea. I think its all gonna depend on how we present it, but there are definitely a lot of terms that could probably benefit from being reviewed

**Comment by nkmlombardi** [comment]
If we didn't use the world asset to explain overarching holdings, would the rest work?

Something distributed on a platform = Token
platform currency = Cryptocurrency

**Comment by kmanc** [comment]
Do we need them to both fit under an overarching term?

**Comment by nkmlombardi** [comment]
It certainly helps when referring to things as a whole.

Blockchain is not dependent on Cryptocurrency, yet it gets bundled in with it when referring to the entire ecosystem (at least to laymen). Tokens depend on cryptocurrency, yet are called all sorts of things.

In both instances, the community lacks a coherent and definitive term to refer to both *the technical ecosystem as a whole (blockchain + cryptocurrency), as well as the economic side; their holdings (cryptocurrency + tokens).

My simple solution to the latter, is referring to your holdings as Crypto assets. If you think that term goes over the head of our readers, we need to find another term.

**Comment by kmanc** [comment]
I do think its a little too much. I think it is a word that sounds sophisticated and (whether it really is or not) will scare people. I re-read your distinction between a CC and a token above, and I'm not sure I understand tbh. I see CC as the overarching term...a crypto-based currency (ie something that can be traded)

**Comment by mattbloom** [comment]
I'd lean towards cryptocurrency. Token feels to me like a voucher for something and not actual possession. I think the word coin (when used or recognized on other sites) will fit nicer with cryptocurrency too.

**Comment by Suhmedoh** [comment]
Cryptocurrency for the overarching concept, bitcoin, ethereum, etc., and token for the sub currencies/tokens that are built on other systems(augur, golem, steem, etc.)

That's the way I've seen it, and I think that's the way it makes the most sense, and I believe token is more prevalent than coin, as far as usage goes.
