### ISSUE TITLE
Cryptocurrency > Exchanges > Limit & Market Orders

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#5]
The cryptocurrency > exchanges section has an overview of exchanges, but no information about how exchanges work (in a general sense). How market and limit orders work and what they are needs to be covered in sub-sections (H2) tags.

**Comment by mattbloom** [comment]
Two things with this topic:
1. Do we want to be teaching how financial trading works? I can see a sentence or two about how exchanges have evolved to offer traditional stock trading features but not sure how important it is.
2. What were you thinking for 'how exchanges work' other than what we have, something like how they move money, cold storage techniques, etc? I don't think we want to build a 'how to invest guide' but just educate one on what happens to their coins after purchasing (on coinbase for example).

**Comment by nkmlombardi** [comment]
Deferred
