### ISSUE TITLE
Cryptocurrency > Economics > Supply & Demand

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/content#6]
We should have an analogy for how supply and demand works with currencies. Especially illustrating how USD & ETH for example will fluctuate as cryptocurrency grows.

**Comment by kmanc** [comment]
@nkmlombardi what's the status here? Do we still think we need an analogy now that the section was rewritten?

**Comment by nkmlombardi** [comment]
I just read it over, looks good. Great work!
